import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
// import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-blue-500 ">{children}</body>
    </html>
  );
}
